version: 2.1
aliases:
  - &restore_npm_cache
    restore_cache:
      key: dependency-cache-{{ checksum "package-lock.json" }}
jobs:
  setup:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - *restore_npm_cache
      - run: mkdir -p ./reports/junit/
      - run:
          name: run fourth circleci app test
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment: 
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/

  lint:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: run fourth circleci lint
          command: npm run lint
      - store_artifacts:
          path: ~/repo/fourth-circle-app-test

  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: print in command line
          command: echo $DUMMY_API_KEY
    
          

workflows:
  version: 2
  entire-app-flow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - lint
            - test
          context: fourthDummySecrets
        
